version: "3.9"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/code
      - ./.firebase:/code/.firebase
    ports:
      - "8989:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - FIREBASE_STORAGE_BUCKET_NAME=xxx.appspot.com
      - FIREBASE_STORAGE_PRODUCTS_FOLDER=images/products
      - FIREBASE_STORAGE_BRANDS_FOLDER=images/brands
      - FIREBASE_STORAGE_CATEGORIES_FOLDER=images/categories
      - FIREBASE_STORAGE_SUBCATEGORIES_FOLDER=images/subcategories
      - GOOGLE_APPLICATION_CREDENTIALS=.firebase/service_account.json
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata/vib:/var/lib/postgresql/data
    ports:
      - "5432:5432"
