# Generated by Django 4.1.3 on 2022-11-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("hot", "Hot"), ("sale", "Sale"), ("normal", "Normal")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("click_count", models.IntegerField(default=0)),
                ("min_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "band",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.band"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
