# Generated by Django 4.1.3 on 2022-12-03 00:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_productcolor_productimage_productsize_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="facebook_contact",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="brand",
            name="followers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="brand",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="instagram_contact",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="brand",
            name="line_contact",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="brand",
            name="created_at",
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="updated_at",
            field=core.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=core.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=core.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="productcolor",
            name="created_at",
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="productcolor",
            name="updated_at",
            field=core.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="created_at",
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="updated_at",
            field=core.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="created_at",
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="updated_at",
            field=core.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="created_at",
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="updated_at",
            field=core.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="created_at",
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="updated_at",
            field=core.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="created_at",
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="updated_at",
            field=core.models.CustomDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=core.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="updated_at",
            field=core.models.CustomDateTimeField(auto_now=True),
        ),
    ]
