# Generated by Django 4.1.3 on 2022-12-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_brand_facebook_contact_brand_followers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
