# Generated by Django 4.1.3 on 2022-12-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_brand_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="brand",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.tag"),
        ),
    ]
