# Generated by Django 4.1.3 on 2022-12-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_brand_priority_brand_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="image_url",
        ),
        migrations.AddField(
            model_name="brand",
            name="image_path",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="image_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
