# Generated by Django 4.1.3 on 2022-12-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_brand_image_url_remove_category_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcolor",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
    ]
