import os

FIREBASE_STORAGE_BUCKET_NAME = os.environ.get("FIREBASE_STORAGE_BUCKET_NAME")
FIREBASE_STORAGE_PRODUCTS_FOLDER = os.environ.get("FIREBASE_STORAGE_PRODUCTS_FOLDER")
FIREBASE_STORAGE_BRANDS_FOLDER = os.environ.get("FIREBASE_STORAGE_BRANDS_FOLDER")
FIREBASE_STORAGE_CATEGORIES_FOLDER = os.environ.get("FIREBASE_STORAGE_CATEGORIES_FOLDER")
FIREBASE_STORAGE_SUBCATEGORIES_FOLDER = os.environ.get("FIREBASE_STORAGE_SUBCATEGORIES_FOLDER")

NO_MAX_UPLOAD_IMAGE = 10
